spring.application.name=api
# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/urbfix_db
spring.datasource.username=urbfix_admin
spring.datasource.password=urbfix_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# Atualiza o banco automaticamente com base nas entidades criadas
spring.jpa.hibernate.ddl-auto=update
# Mostra os comandos SQL no console do IntelliJ (ótimo para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURAÇÕES DO SWAGGER/OPENAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html